package:
  name: bioawk
  version: "1.0"
source:
  fn: bioawk-1.0.tar.gz
  url: https://github.com/lh3/bioawk/archive/v1.0.tar.gz
build:
    number: 1
requirements:
  build:
  run:
test:
  commands:
    - echo "hw" | bioawk '{print}' > /dev/null
about:
  home: https://github.com/lh3/bioawk
  license: Free software license (https://github.com/lh3/bioawk/blob/master/README.awk#L1)
  summary: BWK awk modified for biological data
